[2022-12-10 10:37:51,331] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:37:58,379] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10137
[2022-12-10 10:38:00,568] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:38:00,883] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 3}
[2022-12-10 10:38:00,884] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:01,639] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:38:01,956] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 4}
[2022-12-10 10:38:01,957] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:02,607] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10137
[2022-12-10 10:38:02,846] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 5}
[2022-12-10 10:38:02,847] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:03,677] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"clear"}'
[2022-12-10 10:38:03,865] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 5}
[2022-12-10 10:38:03,866] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:05,345] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10137
[2022-12-10 10:38:05,383] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:05,387] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:06,550] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:06,551] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:23,107] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:38:25,070] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:25,071] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:26,879] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:38:29,268] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:29,269] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:37,162] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:38,474] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:38,476] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:38,531] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:38,958] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:39,294] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:39,601] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:39,780] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:39,781] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:40,333] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:40,334] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:40,665] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:40,666] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:40,970] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:40,971] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:52,177] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:53,189] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:53,608] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:53,931] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:38:54,163] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:54,164] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:54,327] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:54,328] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:54,799] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:54,800] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:38:55,311] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:38:55,312] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:39:23,129] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:39:24,615] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:39:24,616] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:39:25,096] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10093
[2022-12-10 10:39:26,317] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-12-10 10:39:26,318] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:01,366] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:40:05,294] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:05,789] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:07,217] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 2}
[2022-12-10 10:40:07,218] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:07,788] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /api/count
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/root/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '1' for key 'PRIMARY'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 33, in counter
    rsp = update_count(request)
  File "/app/wxcloudrun/views.py", line 78, in update_count
    data.save()
  File "/root/.local/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/root/.local/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/root/.local/lib/python3.8/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/root/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/root/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/root/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/root/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1062, "Duplicate entry '1' for key 'PRIMARY'")
[2022-12-10 10:40:07,800] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /api/count HTTP/1.1" 500 209030
[2022-12-10 10:40:08,861] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:40:10,181] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 2}
[2022-12-10 10:40:10,183] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:10,942] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:12,369] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 4}
[2022-12-10 10:40:12,370] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:12,981] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:13,855] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:14,197] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 6}
[2022-12-10 10:40:14,198] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:14,941] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:15,009] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 8}
[2022-12-10 10:40:15,010] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 22
[2022-12-10 10:40:15,716] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:16,148] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 10}
[2022-12-10 10:40:16,149] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 23
[2022-12-10 10:40:16,711] [views.py:62] [views:update_count] [INFO]- update_count req: b'{"action":"inc"}'
[2022-12-10 10:40:16,967] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 12}
[2022-12-10 10:40:16,968] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 23
[2022-12-10 10:40:18,164] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:40:18,165] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /api/count HTTP/1.1" 200 23
[2022-12-10 10:40:19,436] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:41:02,637] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:41:03,501] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:41:04,302] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:41:04,385] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:41:04,386] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 23
[2022-12-10 10:41:04,449] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:41:04,450] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 23
[2022-12-10 10:41:05,710] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:41:05,711] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 23
[2022-12-10 10:41:14,934] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10143
[2022-12-10 10:41:16,218] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:41:16,219] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 23
[2022-12-10 10:41:17,709] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:41:19,117] [views.py:37] [views:counter] [INFO]- response result: {"code": 0, "data": 14}
[2022-12-10 10:41:19,117] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 23
[2022-12-10 10:42:51,763] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:43:54,478] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:43:55,742] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:43:58,858] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:05,367] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:07,255] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:14,872] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:22,228] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:23,825] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:27,485] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 14, in index
    return render(request, 'index.html')
  File "/root/.local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/root/.local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[2022-12-10 10:44:27,491] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET / HTTP/1.1" 500 72519
[2022-12-10 10:44:27,675] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/wxcloudrun/views.py", line 14, in index
    return render(request, 'index.html')
  File "/root/.local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/.local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/root/.local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[2022-12-10 10:44:27,678] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 72319
[2022-12-10 10:44:47,906] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 10:44:51,221] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 10140
[2022-12-10 10:44:51,375] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 10140
[2022-12-10 10:45:52,975] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
